export const bidang = [
  '-',
  'Pengolahan Citra',
  'Sistem Pakar',
  'Pengolahan Teks',
  'Media Pembelajaran',
  'Estimasi Effort Perangkat Lunak',
  'Sistem Informasi',
  'Kebutuhan Perangkat Lunak',
  'Augmented dan Virtual Reality',
  'Interaksi Manusia dan Komputer',
  'Social Network and Graph',
  'Multimedia dan Grafika',
  'Forensik Digital',
  'Kriptografi',
  'Keamanan Komputer',
  'Sistem Pendukung Keputusan',
  'Machine Learning dan Data Mining',
  'Network dan Sistem Terdistribusi',
];

export const periode = [
  '-',
  'ganjil 2019 / 2020',
  'genap 2019 / 2020',
  'ganjil 2020 / 2021',
  'genap 2020 / 2021',
  'ganjil 2021 / 2022',
  'genap 2021 / 2022',
];

export const dospem = [
  '-',
  'Ardiansyah, S.T., M.Cs',
  'Adhi Prahara, S.Si., M.Cs',
  'Ahmad Azhari, S.Kom., M.Eng',
  'Ali Tarmuji, S.T., M. Cs',
  'Anna Hendri Soleliza Jones, S. Kom, M.Cs.',
  'Ir. Ardi Pujiyanta, M. T.',
  'Andri Pranolo, S.Kom., M. Cs',
  'Arfiani Nur Khusna, S.T., M.Kom.',
  'Dewi Pramudi Ismi, S.T., M.CompSc',
  'Dewi Soyusiawaty, S.T., M.T',
  'Dinan Yulianto, S.T., M.Eng.',
  'Dwi Normawati, S.T., M.Eng.',
  'Eko Aribowo, S.T., M.Kom',
];

export const dosenpengaju = [
  '-',
  'Ardiansyah, S.T., M.Cs',
  'Adhi Prahara, S.Si., M.Cs',
  'Ahmad Azhari, S.Kom., M.Eng',
  'Ali Tarmuji, S.T., M. Cs',
  'Anna Hendri Soleliza Jones, S. Kom, M.Cs.',
  'Ir. Ardi Pujiyanta, M. T.',
  'Andri Pranolo, S.Kom., M. Cs',
  'Arfiani Nur Khusna, S.T., M.Kom.',
  'Dewi Pramudi Ismi, S.T., M.CompSc',
  'Dewi Soyusiawaty, S.T., M.T',
  'Dinan Yulianto, S.T., M.Eng.',
  'Dwi Normawati, S.T., M.Eng.',
  'Eko Aribowo, S.T., M.Kom',
];
